#!/bin/bash
set -euo pipefail

mkdir -p out_medoids out_labels out_qc

###############################
#export OMP_NUM_THREADS=1
#export MKL_NUM_THREADS=1
#export OPENBLAS_NUM_THREADS=1
#export NUMEXPR_NUM_THREADS=1
###############################

CONTAINER_IMAGE="${BL_CONTAINER_IMAGE:-docker://gamorosino/tract_align:v1.0}"

if command -v singularity >/dev/null 2>&1; then
    echo "[main] running with singularity: ${CONTAINER_IMAGE}"
    singularity exec -e "${CONTAINER_IMAGE}" micromamba run -n tract_align  python3 main.py

else
    echo "[main] singularity not found; running main.py directly"
    python3 main.py
fi
